name: mothrly
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.1.2
  geolocator: ^8.2.0
  geocoding: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Group_76.png
    - assets/Plants.png
    - assets/Group_1.png
    - assets/card1p2.png
    - assets/card1p1.png
    - assets/card2p1.png
    - assets/card2p2.png
    - assets/card3p1.png
    - assets/card3p2.png
    - assets/card3p3.png
    - assets/card3p4.png
    - assets/card3p5.png
    - assets/card4p1.png
    - assets/card4p2.png
    - assets/card4p3.png
    - assets/profilepic.png
    - assets/coupon.png
    - assets/logo.png
    - assets/data_image/data1_img.png
    - assets/data_image/data2_img.png
    - assets/data_image/data3_img.png
    - assets/data_image/data4_img.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: General Sans
      fonts:
        - asset: fonts/GeneralSans-Bold.otf
          weight: 700
        - asset: fonts/GeneralSans-BoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/GeneralSans-Extralight.otf
        - asset: fonts/GeneralSans-Extralight.ttf
        - asset: fonts/GeneralSans-ExtralightItalic.otf
        - asset: fonts/GeneralSans-Italic.otf
          style: italic
        - asset: fonts/GeneralSans-Light.otf
        - asset: fonts/GeneralSans-LightItalic.otf
        - asset: fonts/GeneralSans-Medium.otf
        - asset: fonts/GeneralSans-MediumItalic.otf
        - asset: fonts/GeneralSans-Regular.otf
        - asset: fonts/GeneralSans-Semibold.otf
        - asset: fonts/GeneralSans-SemiboldItalic.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
